version: '3'

services:
    drupal:
        image: drupal
        ports:
            - '8080:80'
        volumes:
            - /var/www/html/modules
            - /var/www/html/profiles
            - /var/www/html/themes
            - /var/www/html/sites
        restart: always

    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: example
        restart: always

