#!/bin/bash

docker container run --name postgres -v $(pwd):/var/lib/postgresql/data -e POSTGRES_PASSWORD=pass -d postgres:9.6.1

docker container run --name postgres -v $(pwd):/var/lib/postgresql/data -e POSTGRES_PASSWORD=pass -d postgres:9.6.2

